### ISSUE TITLE
CDC: When `cdc=True`, OUT and SETUP packets are duplicated

### ISSUE THREAD

**Issue by xobs** [im-tomu/valentyusb#14]
```sh
$ make \
    PYTHONPATH=../litex:../..:../migen:../pythondata-misc-tapcfg:../usb-test-suite-cocotb-usb \
    PYTHON_BIN=python3 \
    TARGET=valentyusb \
    TEST_SCRIPT=test-eptri \
    CDC=1
...
  2470.00ns INFO     ..test_control_setup.0x7f1996923670       decorators.py:252  in _advance                        Starting test: "test_control_setup"
                                                                                                                     Description: None
  2470.00ns INFO     cocotb.tb                               host_valenty.py:37   in __init__                        CDC is enabled
  2470.00ns INFO     cocotb.tb.wishbone                          wishbone.py:114  in __init__                        Wishbone Master created, cycle timeout is 20 clock cycles
  4900.00ns INFO     cocotb.tb                                       host.py:226  in host_setup                      Sending setup packet at 5, deadline 5005
 17368.66ns INFO     cocotb.tb                                    monitor.py:85   in _monitor_recv                   Response came after 4.0 bit times
 19460.00ns INFO     cocotb.tb                                       host.py:144  in print_ep                        ep(0, OUT): Got: [128, 128, 128, 128, 128, 128, 128, 128, 6] (expected: [128, 6, 0, 6, 0, 0, 0, 0])
 19460.00ns ERROR    cocotb.regression                         regression.py:327  in handle_result                   Test Failed: test_control_setup (result was TestFailure)
                                                                                                                     Traceback (most recent call last):
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-testbenches/tests/test-eptri.py", line 41, in test_control_setup
                                                                                                                         yield harness.transaction_setup(
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-cocotb-usb/cocotb_usb/host_valenty.py", line 254, in transaction_setup
                                                                                                                         yield self.expect_setup(epaddr_out, data)
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-cocotb-usb/cocotb_usb/host_valenty.py", line 147, in expect_setup
                                                                                                                         assertEqual(expected_data, actual_data,
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-cocotb-usb/cocotb_usb/utils.py", line 38, in assertEqual
                                                                                                                         raise TestFailure("{} vs {} - {}".format(a, b, msg))
                                                                                                                     cocotb.result.TestFailure: [128, 6, 0, 6, 0, 0, 0, 0] vs [128, 128, 128, 128, 128, 128, 128, 128, 6] - SETUP packet not received
 19460.00ns INFO     cocotb.regression                         regression.py:344  in execute                         Running test 3/17: test_control_setup_clears_stall
 19460.00ns INFO     ..setup_clears_stall.0x7f199692a2e0       decorators.py:252  in _advance                        Starting test: "test_control_setup_clears_stall"
                                                                                                                     Description: None
 19460.00ns INFO     cocotb.tb                               host_valenty.py:37   in __init__                        CDC is enabled
 19460.00ns INFO     cocotb.tb.wishbone                          wishbone.py:114  in __init__                        Wishbone Master created, cycle timeout is 20 clock cycles
 24959.12ns INFO     cocotb.tb                                 test-eptri.py:349  in test_control_setup_clears_stall sending data to confirm things are working
 24959.12ns WARNING  cocotb.tb                               host_valenty.py:270  in transaction_data_out            Sending 8 bytes to host
 24990.00ns INFO     cocotb.tb                                       host.py:205  in host_send                       Sending data at 25, deadline 50025
 37462.33ns INFO     cocotb.tb                                    monitor.py:85   in _monitor_recv                   Response came after 4.0 bit times
 44590.00ns INFO     cocotb.tb                                       host.py:144  in print_ep                        ep(0, OUT): Got: [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] (expected: [1, 2, 3, 4, 5, 6, 0, 0])
 44590.00ns ERROR    cocotb.regression                         regression.py:327  in handle_result                   Test Failed: test_control_setup_clears_stall (result was TestFailure)
                                                                                                                     Traceback (most recent call last):
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-testbenches/tests/test-eptri.py", line 350, in test_control_setup_clears_stall
                                                                                                                         yield harness.transaction_data_out(addr, epaddr_out, d)
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-cocotb-usb/cocotb_usb/host_valenty.py", line 277, in transaction_data_out
                                                                                                                         yield self.expect_data(epnum, list(chunk), expected)
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-cocotb-usb/cocotb_usb/host_valenty.py", line 223, in expect_data
                                                                                                                         assertEqual(expected_data, actual_data,
                                                                                                                       File "/mnt/d/Code/Betrusted/valentyusb/test-suite/usb-test-suite-cocotb-usb/cocotb_usb/utils.py", line 38, in assertEqual
                                                                                                                         raise TestFailure("{} vs {} - {}".format(a, b, msg))
                                                                                                                     cocotb.result.TestFailure: [1, 2, 3, 4, 5, 6, 0, 0] vs [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] - DATA packet not correctly received
```

This behavior is observed in current `master`, as well as when run against https://github.com/betrusted-io/valentyusb/tree/cdc-cleanup

When building with `cdc=False`, this behavior is not observed.

**Comment by bunnie** [comment]
Please see https://github.com/antmicro/usb-test-suite-testbenches/pull/19

* 3 dummy cycles needed after receiving a packet in order for a reset to propagate across clock domains
* valenty usb testbench generator was not passing the cdc=cdc argument on to the dut.v generation, and thus, it was defaulting to `False`

**Comment by xobs** [comment]
This is now fixed. Thanks!
